# Bumpy multi-stage Docker build: build app in a Docker image and publish to registry

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureCrUser: 'kadluba'
  azureCrAddress: '$(azureCrUser).azurecr.io'
  dockerImage: 'bumpy:latest'
  dockerTag: '$(azureCrAddress)/samples/$(dockerImage)'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: docker login -u $(azureCrUser) -p $(azureCrPassword) $(azureCrAddress)
      displayName: "Docker ACR Login"
    - script: docker build --rm -f "Bumpy/Dockerfile" -t $(dockerTag) Bumpy
      displayName: "Docker Build"
- stage: Push
  jobs:
  - job: Push
    steps:
    - script: docker push $(dockerTag)
    displayName: "Docker Push Image to ACR"
