# Bumpy multi-stage Docker build: build app in a Docker image and publish to registry

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureCrUser: 'kadluba'
  azureCrAddress: '$(azureCrUser).azurecr.io'
  dockerImage: 'bumpy-webapi:latest'
  dockerTag: '$(azureCrAddress)/samples/$(dockerImage)'

stages:
- stage: BuildWebApi
  jobs:
  - job: "BuildPush"
    displayName: "Build and Push WebApi"
    steps:
    - script:  echo "$(azureCrPassword)" | docker login -u $(azureCrUser) --password-stdin $(azureCrAddress)
      displayName: "Docker ACR Login"
    - script: docker build --rm -f "Dockerfile" -t $(dockerTag) .
      displayName: "Docker WebApi Build"
    - script: docker push $(dockerTag)
      displayName: "Docker Push WebApi Image to ACR"
