# Bumpy multi-stage Docker build: build app in a Docker image and publish to registry

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureCrUser: 'kadluba'
  azureCrAddress: '$(azureCrUser).azurecr.io'
  dockerTagWebApi: '$(azureCrAddress)/samples/bumpy-webapi:latest'
  dockerTagFrontend: '$(azureCrAddress)/samples/bumpy-frontend:latest'

stages:
- stage: Build
  jobs:
  - job: "BuildPushWebApi"
    displayName: "Build and Push WebApi"
    steps:
    - script:  echo "$(azureCrPassword)" | docker login -u $(azureCrUser) --password-stdin $(azureCrAddress)
      displayName: "Docker ACR Login"
    - script: docker build --rm -f "Bumpy.API.WebApi/Dockerfile" -t $(dockerTagWebApi) .
      displayName: "Docker Build"
    - script: docker push $(dockerTagWebApi)
      displayName: "Docker Push Image to ACR"
  - job: "BuildPushFrontend"
    displayName: "Build and Push Frontend"
    steps:
    - script:  echo "$(azureCrPassword)" | docker login -u $(azureCrUser) --password-stdin $(azureCrAddress)
      displayName: "Docker ACR Login"
    - script: docker build --rm -f "Bumpy.Frontend/Dockerfile" -t $(dockerTagFrontend) .
      displayName: "Docker Build"
    - script: docker push $(dockerTagFrontend)
      displayName: "Docker Push Image to ACR"
