
version: '3'
services:
  webapi:
    build: 
      context: .
      dockerfile: Bumpy.API.WebApi/Dockerfile
    expose:
        - "80"
        - "443"

  frontend:
    build: 
      context: .
      dockerfile: Bumpy.Frontend/Dockerfile
    depends_on:
      - webapi
    ports:
        - "8080:80"
        - "8081:443"
